baseURL: ikigai.fyi
languageCode: en-us
title: Ikigai
theme: "PaperMod"

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

# googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Ikigai
  description: "Ikigai company"
  author: ["Vincent Ballet", "Paul Nicolet"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "favicon.ico"
    favicon16x16: "favicon-16x16.png"
    favicon32x32: "favicon-32x32.png"
    apple_touch_icon: "apple-touch-icon.png"

  label:
    text: "Memories"
    # icon: "apple-touch-icon.png"
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: true 
    title: "Memories"
    subtitle: "Widgets for Strava"
    imageUrl: "cover.png"
    imageWidth: 120
    imageHeight: 120
    imageTitle: "memories icon"
    buttons:
      - name: Download
        url: https://apps.apple.com/us/app/memories-widget-for-strava/id6448870765

  # home-info mode
  # homeInfoParams:
  #   Title: "Memories: Widgets for Strava \U0001F44B"
  #   Content: Welcome to my blog

  # socialIcons:
  #   - name: twitter
  #     url: "https://twitter.com/"
  #   - name: stackoverflow
  #     url: "https://stackoverflow.com"
  #   - name: github
  #     url: "https://github.com/"

  # analytics:
  #   google:
  #     SiteVerificationTag: "XYZabc"

  # cover:
    # hidden: false # hide everywhere but not in structured data
    # hiddenInList: false # hide on list pages and home
    # hiddenInSingle: false # hide on single page

  # editPost:
    # URL: "https://github.com/<path_to_repo>/content"
    # Text: "Suggest Changes" # edit text
    # appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  # fuseOpts:
  #   isCaseSensitive: false
  #   shouldSort: true
  #   location: 0
  #   distance: 1000
  #   threshold: 0.4
  #   minMatchCharLength: 0
  #   keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: contact
      name: Contact
      url: "mailto:vincent.ballet@me.com"
      weight: 10
    - identifier: download
      name: Download
      url: https://apps.apple.com/us/app/memories-widget-for-strava/id6448870765
      weight: 20

# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
# markup:
#   highlight:
#     noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai

